DEFAULT_LIVESTOCK_ITEMS = [
    "Meat of asses, fresh or chilled (indigenous)",
    "Meat of buffalo, fresh or chilled (indigenous)",
    "Meat of camels, fresh or chilled (indigenous)",
    "Meat of chickens, fresh or chilled (indigenous)",
    "Meat of ducks, fresh or chilled (indigenous)",
    "Meat of geese, fresh or chilled (indigenous)",
    "Meat of goat, fresh or chilled (indigenous)",
    "Meat of mules, fresh or chilled (indigenous)",
    "Meat of other domestic camelids, fresh or chilled (indigenous)",
    "Meat of pig with the bone, fresh or chilled (indigenous)",
    "Meat of pigeons and other birds n.e.c., fresh, chilled or frozen (indigenous)",
    "Meat of rabbits and hares, fresh or chilled (indigenous)",
    "Meat of sheep, fresh or chilled (indigenous)",
    "Meat of turkeys, fresh or chilled (indigenous)",
    "Horse meat, fresh or chilled (indigenous)",
    "Hen eggs in shell, fresh",
    "Eggs from other birds in shell, fresh, n.e.c.",
    "Game meat, fresh, chilled or frozen",
    "Meat of cattle with the bone, fresh or chilled",
    "Meat of chickens, fresh or chilled",
    "Meat of goat, fresh or chilled",
    "Meat of pig with the bone, fresh or chilled",
    "Meat of sheep, fresh or chilled",
    "Meat of turkeys, fresh or chilled",
    "Meat of camels, fresh or chilled",
    "Horse meat, fresh or chilled",
    "Meat of rabbits and hares, fresh or chilled",
    "Natural honey",
    "Other meat n.e.c. (excluding mammals), fresh, chilled or frozen",
]
