---
format:
  html:
    embed-resources: true
    standalone: true
    code-fold: true           # Fold code by default in HTML
    code-summary: "Show code"
  pdf:
    echo: false              # Hide code by default in PDF
  docx:
    echo: false              # Hide code by default in Word
---

# **Ecosystem Service: crop provision, a provisioning service of crop**

Main contributors: Marta Sylla, Lijing Wang, Ryan McWay

This section outlines how we assess and value food provision as an ecosystem service within the GEP framework. The analysis focuses specifically on food provision provided by terrestrial ecosystems. This analysis does not include any aquatic ecosystem; aquaculture/fisheries is covered in a different section of the GEP manuscript. By estimating and valuing crop provision, we aim to capture the ecosystem contribution to commercial crop agricultural practices.

Crop production is defined as a contribution of the ecosystem to agricultural production of crops (United Nations et al., 2021). The contribution of the ecosystem has effective biophysical impact and consecutive economic influence. Researchers often applied these two perspectives: biophysical and economic. Biophysical perspective starts at looking at the biophysical processes or biological production functions and tries to disentangle ecosystem and human contributions. Very often the common units of energy or biomass, water inputs are used. In the economic perspective, the common monetary units are used. Crop production belongs to the provisioning group of ecosystem services (CICES Version 5.1), as well as is characterized as material contribution by the classification suggested to the concept of nature contributions to people (Brauman et al 2020).

This is a final product that enters the economy via the agricultural sector. Further modifications or processing of the initial/raw products are included in the GDP of the economic sector of Agriculture, Forestry, Fishing and Hunting, but also other sectors down the value chain. It should be noted, however, that according to the global study farmers receive, on average, 27% of the money consumers spend on food eaten at home, while they receive a significantly smaller share of the expenditure on food consumed outside home (Yi et al., 2021). This percentage varies across countries and regions, as well as changes with the quality of the raw product.

**Data and Methods**

We estimate gross ecosystem product (GEP) for crop provision for the year 2019 as:\
$$
\mathrm{GEP crop}_{\text{c,k,t}} = \sum_{c,k,t} \left( \mathrm{GPV}_{c,k,t} \cdot \lambda_{c,t10} \right)
$$
, where

GEP crop c,k,t is the agricultural ecosystem contribution for country c, crop item k and given year t,

GPVk,t is the FAO’s gross production value for country c, crop item k and given year ,

λc,t10 is the CWON land rent representing ecosystem contribution for country c, decade t10,

This value is aggregated at the national level for a given year (in this case, 2019). The summation can represent global GEP for food provision when aggregated across all countries, crop items and year.

This formula and method follows the Changing Wealth of Nations method presented in the [2024 report](https://documents1.worldbank.org/curated/en/099100824155021548/pdf/P178446-7dfe6e92-9cf0-4d24-ad25-20b1320904c2.pdf) (World Bank, 2024). Lambda (λ) is “proxied by land cost shares provided by the International Agricultural Productivity database for each country and each decade. For countries where rental rates vary across decades, annual values are assumed to be constant within each decade” (World Bank, 2024). Agricultural land is further subdivided into pasture or cropland, therefore land rates are disaggregated into livestock or crop production. We do not distinguish between organic and non-organic farming, as well as intensive/extensive types of farming. In the CWON report of 2021 (Source: CWON 2021: Methods and Data, p. 48) the pastures were divided into intensive and extensive pastureland and the rental rates for extensive pasture were twice as high as for intensive. The rental rates for intensive pasture and cropland were the same. However, the data was provided by regions of several countries clustered together. Therefore, the CWON 2024 methodology constitutes a major improvement in terms of accuracy and timeframe, losing the artificially doubling the rent for extensive pastureland.

**Validation**

The applied method follows the CWON methodology for estimating the value of natural capital rents. For agriculture, the natural resource is land and the crop rents represent ecosystem contribution. We compared our results with the CWON 2024 for global results for the year 2019. CWON’s results are about 5% lower than ours, even though we use the same input data and values for lambda.

**References:**

1.  K.A. Brauman, L.A. Garibaldi, S. Polasky, Y. Aumeeruddy-Thomas, P.H.S. Brancalion, F. DeClerck, U. Jacob, M.E. Mastrangelo, N.V. Nkongolo, H. Palang, N. Pérez-Méndez, L.J. Shannon, U.B. Shrestha, E. Strombom, & M. Verma,Global trends in nature’s contributions to people, *Proc. Natl. Acad. Sci. U.S.A.* 117 (51) 32799-32805, <https://doi.org/10.1073/pnas.2010473117> (2020).\
2.  Yi, J., Meemken, EM., Mazariegos-Anastassiou, V. *et al.* Post-farmgate food value chains make up most of consumer food expenditures globally. *Nat Food* **2**, 417–425 (2021). <https://doi.org/10.1038/s43016-021-00279-9>\
3.  World Bank (2024). The Changing Wealth of Nations: Revisiting the Measurement of Comprehensive Wealth. <https://documents1.worldbank.org/curated/en/099100824155021548/pdf/P178446-7dfe6e92-9cf0-4d24-ad25-20b1320904c2.pdf>\
4.  United Nations et al. (2021). System of Environmental-Economic Accounting— Ecosystem Accounting (SEEA EA). White cover publication, pre-edited text subject to official editing. Available at: https://seea.un.org/ecosystem-accounting.